clibrary-web/src/main/java/org/clibrary/db/bean/BorrowerFacade.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.clibrary.db.bean;

import org.clibrary.db.hibernate.Borrower;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

/**
 *
 * @author ascott
 */
@Stateless
public class BorrowerFacade extends AbstractFacade<Borrower> {

    @PersistenceContext(unitName = "au.net.ascott_clibrary-web_war_1.0-SNAPSHOTPU")
    private EntityManager em;

    @Override
    protected EntityManager getEntityManager() {
        return em;
    }

    public BorrowerFacade() {
        super(Borrower.class);
    }  
}

clibrary-web/src/main/java/org/clibrary/db/bean/CategoryFacade.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.clibrary.db.bean;

import org.clibrary.db.hibernate.Category;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

/**
 *
 * @author ascott
 */
@Stateless
public class CategoryFacade extends AbstractFacade<Category> {

    @PersistenceContext(unitName = "au.net.ascott_clibrary-web_war_1.0-SNAPSHOTPU")
    private EntityManager em;

    @Override
    protected EntityManager getEntityManager() {
       return em;
    }

    public CategoryFacade() {
        super(Category.class);
    }
    
}

clibrary-web/src/main/java/org/clibrary/db/bean/LoanFacade.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.clibrary.db.bean;

import org.clibrary.db.hibernate.Loan;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

/**
 *
 * @author ascott
 */
@Stateless
public class LoanFacade extends AbstractFacade<Loan> {

    @PersistenceContext(unitName = "au.net.ascott_clibrary-web_war_1.0-SNAPSHOTPU")
    private EntityManager em;

    @Override
    protected EntityManager getEntityManager() {
       return em;
    }

    public LoanFacade() {
        super(Loan.class);
    }
    
}

clibrary-web/src/main/java/org/clibrary/db/jsf/BorrowerController.java
package org.clibrary.db.jsf;

import org.clibrary.db.hibernate.Borrower;
import org.clibrary.db.jsf.util.JsfUtil;
import org.clibrary.db.jsf.util.JsfUtil.PersistAction;
import org.clibrary.db.bean.BorrowerFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("borrowerController")
@SessionScoped
public class BorrowerController implements Serializable {

    @EJB
    private BorrowerFacade ejbFacade;
    private List<Borrower> items = null;
    private Borrower selected;

    public BorrowerController() {
    }

    public Borrower getSelected() {
        return selected;
    }

    public void setSelected(Borrower selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private BorrowerFacade getFacade() {
        return ejbFacade;
//        return null;
    }

    public Borrower prepareCreate() {
        selected = new Borrower();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("BorrowerCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("BorrowerUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("BorrowerDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Borrower> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Borrower getBorrower(java.lang.String id) {
        return getFacade().find(id);
    }

    public List<Borrower> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Borrower> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Borrower.class)
    public static class BorrowerControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            BorrowerController controller = null;
            Object obj = null;
            try{
                if (value == null || value.length() == 0) {
                    return null;
                }
                controller = (BorrowerController) facesContext.getApplication().getELResolver().
                        getValue(facesContext.getELContext(), null, "borrowerController");
                obj = controller.getBorrower(getKey(value));
            } catch (Exception e){
                FacesMessage msg = new FacesMessage("borrowerController error: " + e);
                FacesContext.getCurrentInstance().addMessage(null, msg); 
            }
            return obj;
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Borrower) {
                Borrower o = (Borrower) object;
                return getStringKey(o.getBorrowerid());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Borrower.class.getName()});
                return null;
            }
        }

    }

}

clibrary-web/src/main/java/org/clibrary/web/jsf/controller/CategoryController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.clibrary.web.jsf.controller;

import org.clibrary.db.hibernate.Category;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.primefaces.event.CellEditEvent;
import org.primefaces.event.ResizeEvent;
import org.primefaces.event.RowEditEvent;
import org.primefaces.event.SelectEvent;

/**
 *
 * @author ascott
 */
@Named(value = "myCategoryController")
@SessionScoped
public class CategoryController implements Serializable {
 
    @EJB
    private org.clibrary.db.bean.CategoryFacade ejbFacade;
    static final long serialVersionUID = -1L;
    private Category current = new Category();
    private List<Category> categoryPageList = new ArrayList<>();
    private final String instructions = "none";
    private static final boolean error = false;

    /**
     * Creates a new instance of AddCategory
     */
    public CategoryController() {
    }
    
    /**
     * Saves a new Category
     * @return a string
     */  
    public String Save() {
        try{
            ejbFacade.create(current); //Category.java called ere this call
            current = new Category();
            FacesMessage msg = new FacesMessage("Category " + current.getCategoryName() + " created");
            FacesContext.getCurrentInstance().addMessage(null, msg);
        } catch (Exception e){
            FacesMessage msg;
            int a = e.getCause().getCause().getCause().getCause().getLocalizedMessage().indexOf("Detail") +12;
            if(a > 0){
                String b = e.getCause().getCause().getCause().getCause().getLocalizedMessage().substring(a);
                msg = new FacesMessage("Error: " + b);
            }else {
                msg = new FacesMessage(e.toString());
            }
            FacesContext.getCurrentInstance().addMessage(null, msg);
        }
        return "";
    }
    
    public String getInstructions(){ 
        return instructions;
    } //provides instructions on how to delete/update categories which are assigned to resources
    
    /*public List<String> getUnusedCategoryList(){
        int counter = 0;
        ResultSet resultset = null;
        PreparedStatement preparedStatement = null;
        try{
            Connection connection = DBConn.getDBConn();
            preparedStatement = connection.prepareStatement("Select \"Category\".\"CategoryName\" "
             + "from public.\"Category\" " +
            "where \"Category\".\"CategoryID\" not in( " +
            "select \"Resource\".\"CategoryID\" " +
            "from public.\"Resource\")");
            unusedCategoryList.clear();
            resultset = preparedStatement.executeQuery();
            while(resultset.next()){
                unusedCategoryList.add(resultset.getString(1));
                counter++;
            } 
            
            if(counter==0){
               instructions =  "There are no categories you can currently delete";
            } else{
               instructions = "NB You can only remove or change the following categories (those that are not assigned to resources). To change other categories go to the 'Resources by Category' report, note all the resources which have the category you want to change, then go to the 'Browse Resources' form and give those resources a different category. Then return to this form and change or remove the category.";
            }
            System.out.println("cc ctr="+ counter + " " + instructions);
        } catch(SQLException ex){
            String msg = "";
            Throwable cause = ex.getCause();
            if (cause != null) {
                        msg = cause.getLocalizedMessage();
            }
            if (msg.length() > 0) {
                        JsfUtil.addErrorMessage(msg);
            } else {
                        JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("SQLError"));
            }
        } finally{
            try{
                if(!resultset.isClosed()){
                    resultset.close();
                }
                preparedStatement.close();
            } catch(SQLException ex){
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("SQLError"));
                }
            } catch(Exception ex){
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("SQLError"));
                }
            }
           
        } 
        return unusedCategoryList;
    made redundant when editCategories.xhtml finally enabled users to delete categories
    }*/
    
    public String Delete(){
        try{
            ejbFacade.remove(getSelectedCategory());
            FacesMessage msg = new FacesMessage("Category '" + current.getCategoryName() + "' deleted");
            FacesContext.getCurrentInstance().addMessage(null, msg);
        } catch(Exception e){
            FacesMessage msg;
            int a = e.getCause().getCause().getCause().getCause().getLocalizedMessage().indexOf("Detail") +12;
            if(a > 0){
                String b = e.getCause().getCause().getCause().getCause().getLocalizedMessage().substring(a);
                msg = new FacesMessage("Error: " + b);
            }else {
                msg = new FacesMessage(e.toString());
            }
            FacesContext.getCurrentInstance().addMessage(null, msg);
        }    
        return "";
    }
    
    public String Update(String cat){
        try{
        ejbFacade.edit(current);
        } catch(Exception e){
             FacesMessage msg;
            int a = e.getCause().getCause().getCause().getCause().getLocalizedMessage().indexOf("Detail") +12;
            if(a > 0){
                String b = e.getCause().getCause().getCause().getCause().getLocalizedMessage().substring(a);
                msg = new FacesMessage("Error: " + b);
            }else {
                msg = new FacesMessage(e.toString());
            }
            FacesContext.getCurrentInstance().addMessage(null, msg);       
        }
        return "";
    }
    
    public void onRowSelect(SelectEvent event) {
        Object obj = event.getObject();
        Category category = (Category) obj;
        ejbFacade.edit(category);
    }
    
    public void onRowEdit(RowEditEvent event) {
        Object obj = event.getObject();
        Category category = (Category) obj;
        ejbFacade.edit(category);
        System.out.println("cc onrowEdit " + event.getComponent().getId() + " "  + event.getSource().toString());
    }
    
    public void onRowEditCancel(RowEditEvent event) {
        FacesMessage msg = new FacesMessage("Edit Cancelled");
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }
    
    public void onCellEdit(CellEditEvent event) {       
        Object oldValue = event.getOldValue();
        Object newValue = event.getNewValue();       
        if(newValue != null && !newValue.equals(oldValue)) {          
        }       
    }
    
    private Category selectedCategory;
    public Category getSelectedCategory(){
        return selectedCategory;
    }
    
    public void setSelectedCategory(Category selectedCategory){
        this.selectedCategory = selectedCategory;
    }
    
    public String loadCategories() {
        categoryPageList.clear();
        //On a Windows PC:\Users\DL\workspace\clibrary3-db\src\main\java\org\clibrary\db\hibernatequeries
        categoryPageList.addAll(ejbFacade.findAll());
        return "";
    }

    public void layoutResizeEvent(ResizeEvent event) {
        System.out.println("The layout has been sized " + event.getComponent());
    }

    /**
     * @return the current category
     */
    public Category getCurrent() {
        return current;
    }

    /**
     * @param current the current category to set
     */
    public void setCurrent(Category current) {
        this.current = current;
    }

    /**
     * @return the categoryPageList
     */
    public List<Category> getCategoryCategoryPageList() {
        loadCategories();
        //Comparator<? super Category> cmprtr = null;
        Collections.sort(categoryPageList, new Comparator<Category>(){
            @Override
            public int compare(Category t, Category t1) {
                return t.getCategoryName().compareToIgnoreCase(t1.getCategoryName());
            }
        });
        return categoryPageList;
    }

    /**
     * @param categoryPageList the categoryategoryPageList to set
     */
    public void setCategoryPageList(List<Category> categoryPageList) { 
        this.categoryPageList = categoryPageList;
    }
}

clibrary-web/src/main/webapp/GeneralStatisticsReport.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    template="layout/template.xhtml">
    <ui:define name="content">
        <h:form id="GeneralStatsReport">
            <f:view contentType="text/html">
            <p:growl id="GenStatsMessages" showSummary="true" severity="info,warn,error,fatal" life="6000"/>              
            <h1>General Statistics Report</h1> 
            <table border="1">
                <tbody>
                    <ui:repeat var="gsr" value="#{genStatisticsReport.list}">
                    <tr>
                        <td>#{gsr.one}</td>
                        <td>#{gsr.two}</td>	
                    </tr>	
                    </ui:repeat>
                </tbody>
            </table> 
            </f:view>
        </h:form>    
    </ui:define>
</ui:composition>

clibrary-web/src/main/webapp/Help.xhtml
<ui:composition
xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    template="layout/template.xhtml">
    <body> 
        <ui:define name="content">
            <h:form id="Help">
                <p:growl id="HelpMessages" showSummary="true" severity="info,warn,error,fatal" life="6000"/>                
                
                <h1>Help</h1>
		<div id="index">
                    <table style="border-right: black;" cellpadding="7"><tr>
                            <td style="border-right: activeborder solid"><a href="#unfound">Error Message</a></td>
			<td style="border-right: activeborder solid"><a href="#on">Start the computer</a></td>
                        <td style="border-right: activeborder solid"><a href="#borrow">Check out a resource</a></td>
                        <td style="border-right: activeborder solid"><a href="#return">Check in a resource</a></td>
                        <td><a href="#off">Turn off the computer</a></td>
			</tr></table>
		</div>
                <hr/><br />
		<table>
			<tr><th><a name="unfound"></a>Error Message: File not found</th></tr>
                        <tr><td>Print what is on the screen or save the screen contents to a file (use the "prt sc" button on the computer) and inform the Librarian.<br/>
                                Include: 
                                <ol>
                                    <li>The date the problem happened</li>
                                    <li>Who was involved</li>
                                    <li>What happened just before the problem, e.g. I clicked on the "loan" button to loan out a resource and got the error message: "(enter the message here)"</li>
                                    <li>What you did about it, e.g. I recorded the loan details on paper and filed the paper</li>
                                </ol>
                            </td></tr>
			
                        <tr><th><a name="on"></a>How to start the computer</th></tr>
                        <tr><td><ol>
                            <li>Switch on the power at the wall switch</li><br />
                            <li>Push the computer's power button</li><br />
                            <li>Type in the password</li><br />
                        </ol></td></tr>
                        
                        <tr><th><a name="borrow"></a>How to check out a resource</th></tr>
                        <tr><td><ol>
                            <li>Ask for the person's name</li><br />
                            <li>Click on "Borrow" on the menu</li><br />
                            <li>Type in the person's surname(it can be in upper, lower or mixed case, all or part of the name)</li><br />
                            <li>(To search by the person's Christian name use the tab key or click in the box under the "Xian Name" column)</li>
                            <li>Click on the circle to the left of the name of the person borrowing</li><br />
                            <li>Click on the 'Loan' button</li><br />
                            <li>Scan the resource's barcode</li><br />
                            <li>Add comments if desired</li>
                            <li>Click on the "Save" button</li>
			    <li>NB Please check the resource has been checked out. The new loan's details should appear at the top of the list of the user's loans.</li>
                        </ol></td></tr>
                        
                        <tr><th><a name="return"></a>How to check in a resource</th></tr>
                        <tr><td><ol>
                            <li>Click on 'return' on the library menu</li><br />
                            <li>Click on the resource's barcode</li><br />
                            <li>Scan the resource's barcode</li><br />
                      	    <li>NB Please check the resource has been checked in. For DVDs and CDROMs please check the correct resource is in the case and it is undamaged.</li>
                        </ol></td></tr>
                        
                        <tr><th><a name="off"></a>How to turn off the computer</th></tr>
                        <tr><td><ol>
                            <li>Click on the blue button on the lower left hand corner of the computer screen</li><br />
                            <li>Click on the red 'leave'</li><br />
                            <li>click on the red 'shutdown'</li><br />
                            <li>Switch off the power at the wall switch</li><br />
                        </ol></td></tr>                       
		</table>
            </h:form>     
	</ui:define>	
    </body>
</ui:composition>

clibrary-web/src/main/webapp/LoansForYear.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
        xmlns:p="http://primefaces.org/ui"> 
    <h:outputStylesheet name="charts/charts.css" library="primfaces"></h:outputStylesheet>
    
    <h:head>
        <title>Resource Category Report</title>
        <link rel="Stylesheet" href="javax.faces.resource/charts/charts.css.jsf?ln=primefaces" />
    </h:head>
<h:body>
    <h:form>
        <title>Resource Category Report</title>
        <div align="center">
            <p:panel>
                <p:chart type="bar" id="content" model="#{chart.pcm}" style="width:600px;height:450px" />
            </p:panel>
        </div>
               
    </h:form>
</h:body>
</html>

clibrary-web/src/main/webapp/SurnameLoansReport.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    template="layout/template.xhtml">
        <ui:define name="content">
            <h:form id="FamilyLoansReport">
                <p:growl id="FamilyLoansMessages" showSummary="true" severity="info,warn,error,fatal" life="6000"/>             
                
                <h1 style="background-color: aliceblue">Loans For All #{myLoanController.selectedBorrower.lastname}s </h1> 
                <table border="1" cellpadding="5">
			    	<thead>
				    <tr>
                                            <th>Name</th>
                                            <th>Resource (Category)</th>
                                            <th>Date Borrowed</th>
				    </tr>
				</thead>
				<tbody>
                                    <ui:repeat var="name" value="#{myLoanController.surnameLoansList}">
		       			<tr>
                                            <td>#{name.one}</td>
                                            <td>#{name.two}</td>
                                            <td>#{name.three}</td>
		       			</tr>
                                    </ui:repeat>
		      		</tbody>
		      	</table>                    
            </h:form>                       
        </ui:define>
</ui:composition>

clibrary-web/src/main/webapp/editCategories.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    template="layout/template.xhtml">

    <f:metadata>
        <f:viewAction action="#{myCategoryController.loadCategories()}"/>
    </f:metadata>
    <ui:define name="content">
        <h:form id="editCategoriesForm">
            <p:growl id="editCategoriesMessages" showSummary="true" severity="info,warn,error,fatal" life="6000"/>
            <p:dataTable id="editCategoriesDataTable" 
                editable="true" 
                emptyMessage="No categories found"         
                value="#{myCategoryController.categoryCategoryPageList}" 
                paginator="true" 
                rowKey="#{myCategoryController.current.categoryID}"
                rows="11"
                var="cat"
                selection="#{myCategoryController.selectedCategory}" 
                filteredValue="#{myCategoryController.categoryCategoryPageList}">
                
                <p:column selectionMode="single" selectRow="true" headerText="Pick" width="50"></p:column>
                
                <p:ajax event="rowSelect" listener="#{myCategoryController.onRowSelect}" />
                <p:ajax event="rowEdit" update="editCategoriesDataTable" listener="#{myCategoryController.onRowEdit}" immediate="true" />    
                <p:ajax event="rowEditCancel" update="editCategoriesDataTable" listener="#{myCategoryController.onRowEditCancel(event)}" />
                <p:ajax event="cellEdit" update="editCategoriesDataTable" listener="#{myCategoryController.onCellEdit}" immediate="true" />
                
                <p:column id="CategoryIDColumn" headerText="ID" width="50" visible="false">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{cat.categoryID}" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText id="CategoryID"
                                maxlength="25" tabindex="1" value="#{cat.categoryID}"/>
                            <p:message id="CategoryIDMessage" for="CategoryID"/>
                        </f:facet>
                    </p:cellEditor>
                </p:column>
                
                <p:column id="CategoryNameColumn" headerText="Categories">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{cat.categoryName}" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText id="CategoryName" required="true" requiredMessage="Category name must be provided." 
                                maxlength="25" tabindex="2" value="#{cat.categoryName}"/>
                            <p:message id="CategoryNameMessage" for="CategoryName"/>
                        </f:facet>
                    </p:cellEditor>
                </p:column>
                
               <p:column id="CategoryCodeColumn" headerText="Symbols">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{cat.code}" escape="false" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText id="CategoryCode" maxlength="105" tabindex="3" value="#{cat.code}" style="font: fontawesome; text-shadow: 0 0 0 yellow;"/>
                            <p:message id="CategoryCodeMessage" for="CategoryCode"/>
                        </f:facet>
                    </p:cellEditor>
                </p:column>
                
                <p:column  id="editColumn" width="60" headerText="Edit">
                    <p:tooltip for="editColumn" value="Click here to change category details"></p:tooltip>
                    <p:rowEditor/>
                </p:column>
                
                 <f:facet name="footer">
                    <p:commandButton value="Delete" tabindex="4" icon="ui-icon-trash" update="CategoryIDMessage,CategoryNameMessage,CategoryCodeMessage" action="#{myCategoryController.Delete}" />
                    <p:commandButton value="Help" icon="ui-icon-help" action="categoryHelp"></p:commandButton>
                </f:facet>   
            </p:dataTable>
            
            
        </h:form>
    </ui:define>

</ui:composition>